### ISSUE TITLE
Select: when "constrained" without width shouldn't break

### ISSUE THREAD

**Issue by fdefelici** [fdefelici/react-bootstrap-combobox#105]
If you put Select component within an html container without setting the width property, it breaks as follow:
![immagine](https://user-images.githubusercontent.com/24794993/71413499-c3a89300-2652-11ea-8f68-f704e8a7dc62.png)

The expected behaviour should be that "down arrow" stay inline with the text, eventually overlapping:
![immagine](https://user-images.githubusercontent.com/24794993/71413591-2bf77480-2653-11ea-9336-be49751f34ed.png)

**Comment by sickk** [comment]
![image](https://user-images.githubusercontent.com/2381217/71512490-baa80380-2896-11ea-94eb-2ebb8a659553.png)

The menu width should be separated from button,  shouldn't it? @fdefelici 

I had to resize the loading gif from 15x15 to 10x10 to fit better

**Comment by fdefelici** [comment]
IMHO, the previous behaviour shouldn't change (that is, button and menu should have the same width).
Rather, no matter the size of the icon or the width of the widget (is set or if inherited/constrained by the parent), the icon element should always "overlap" the text element.

**Comment by sickk** [comment]
Ok, but when in the menu we have elements with icon, which is the correct visualization?
Cause we have, for example, **[apple icon] [text] [check icon]** buth with a too small menu, all elements will be overlapped

**Comment by fdefelici** [comment]
Should be the user to take care of it given the "right" width to the
widget. Eventually in the scenario you described we can make Selection icon
overlap the text.

Anyway the important is the widget layout should never break (in multiple
line as this issue)

Il ven 27 dic 2019, 12:23 sickk <notifications@github.com> ha scritto:

**Comment by sickk** [comment]
I'm still fighting with the css. 
The max result is:
![image](https://user-images.githubusercontent.com/2381217/71523292-ad0b7180-28c8-11ea-9e78-75f3d0d29e66.png)

If I reach the result with "position: absolute", hidden items appears, for example

**Comment by fdefelici** [comment]
As I said, we could leave this menu scenario, to the user. The latter should assign correct width to the widget in order so show menu properly. 

Instead it should not break on the button. Do we address this issue?

**Comment by sickk** [comment]
The caret, as you can see in the screenshot, doesn't break the button

**Comment by fdefelici** [comment]
ok for me
