### ISSUE TITLE
Allow icon configuration within input

### ISSUE THREAD

**Issue by fdefelici** [fdefelici/react-bootstrap-combobox#125]
Add possibility to configure an icon within the widget on the left. 
Icon could be:
* a bootstrap icon, or
* a custom icon / html element

Here an example:
![immagine](https://user-images.githubusercontent.com/24794993/72662119-7914ff00-39e3-11ea-8be5-7b27e18c4aed.png)

This feature could be added to both widget: Select and Autocomplete.

**Comment by bolognesimarco** [comment]
icons added
