### ISSUE TITLE
[Autocomplete] there is no Orientation for dropdown menu

### ISSUE THREAD

**Issue by Crystopher** [fdefelici/react-bootstrap-combobox#129]
**Is your feature request related to a problem? Please describe.**
Should be interesting to have a property to set the orientation of dropdown-menu, because actually the menu has only the orientation left to right. When i have the Autocomplete object on the right of the screen, there's a strange graphical effect that render the dropdown menu offscreen if "**dropdownWidth**" is greater than Autocomplete's width.

**Describe the solution you'd like**
The solution is to have a property to specify the orientation. Something like **_orientation={"right"}_** or **_orientation={"left"}_**

**Additional context**
As a workaround i changed the dropdown-menu style used by Autocomplete object:
`
.dropdown-menu {
    float: right;
    right: 0;
    left: auto;
}
`

**Comment by Crystopher** [comment]
This is actual behaviour
![image](https://user-images.githubusercontent.com/10629007/90021819-0b4b6000-dcb2-11ea-92c7-9b473f52e435.png)

Should be like this:
![image](https://user-images.githubusercontent.com/10629007/90021948-303fd300-dcb2-11ea-8e0d-20168099a6ae.png)

**Comment by fdefelici** [comment]
we could either add this feature to the Select widget

**Comment by fdefelici** [comment]
eventually property could be called **dropdownAlign**

**Comment by Crystopher** [comment]
added property **dropdownAlign** that can assume "right" or "left" value. Default is left.

**Comment by Crystopher** [comment]
updated **example** project in source

**Comment by Crystopher** [comment]
update documentation for correct usage

**Comment by Crystopher** [comment]
implemented and merged on **v1.12.0** branch

**Comment by Crystopher** [comment]
added unit tests
