### ISSUE TITLE
Decouple Item Label from its value

### ISSUE THREAD

**Issue by fdefelici** [fdefelici/react-bootstrap-combobox#34]
Separate item VALUE from the LABEL shown to the user.

Basically data object should contains label-value pairs for each item.

Eventually we could make VALUE optiona. This means if just LABEL is valued, the label is used also as VALUE

**Comment by sickk** [comment]
Code completed; to do documentation.

**Comment by fdefelici** [comment]
Add also a second combobox in the example showing this feature.

Eventually above each combo we can put a title to name the showcase
